### ISSUE TITLE
Going from a `(OwnedProcess, BorrowedProcessModule)` to a `OwnedProcessModule`

### ISSUE THREAD

**Issue by philpax** [OpenByteDev/dll-syringe#1]
Hi there! A friend and I have been using your crate for our projects and loving it - it's so much nicer than the crappy C++ injectors we used to repeatedly hack into shape 😅 

I have a function A that launches an application (`OwnedProcess`), injects a module into it with a helper function B that takes a `BorrowedProcess` (returns `BorrowedProcessModule`), and I'd like to return a `OwnedProcessModule` from A. 

Unfortunately, there doesn't seem to be a way to fuse these together other than using `unsafe { ProcessModule::new_unchecked(process, pm.handle()) }` which is a bit gnarly. Is it possible for you to add a utility for this?

Thanks 🙏

**Comment by philpax** [comment]
Actually, might be a moot point: there's not really a way to return a `BorrowedProcessModule` from `B` as the `Syringe` used to provide the `process` for the module is dropped within the function.

The reason I used a `BorrowedProcess` for my helper function was because there was no way to go from a `OwnedProcessModule` to `BorrowedProcessModule` for passing into `syringe.get_procedure`; perhaps this is best solved with `OwnedProcessModule::borrowed`?

**Comment by OpenByteDev** [comment]
I dont think a utility to go from `(OwnedProcess, BorrowedProcessModule)` to `OwnedProcessModule` is needed as you can use [`BorrowedProcessModule::try_to_owned`](https://docs.rs/dll-syringe/latest/dll_syringe/process/struct.ProcessModule.html#method.try_to_owned).

As for your second comment: I agree that something like `OwnedProcessModule::borrowed` would be nice and I will add it in.

**Comment by philpax** [comment]
Thank you, that's much appreciated!
