### ISSUE TITLE
`The specified module could not be found.` error shows up even though the DLL exists.

### ISSUE THREAD

**Issue by TechStudent10** [OpenByteDev/dll-syringe#17]
I am compiling a 64-bit program to be injected into a 32-bit program (yes I have the feature flag on).

When I attempt to use `syringe.inject` with a valid path, it fails with the following message:

```rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RemoteIo(Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." })', src\main.rs:11:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I can confirm that the DLL I am inputting exists and should work. I've tried absolute and relative paths but it still will not load. How might I fix this?

**Comment by OpenByteDev** [comment]
So your injector is 64-bit and both the payload and target is 32-bit?

**Comment by OpenByteDev** [comment]
Can you try to load your dll with the same path in a small test program using [`LoadLibraryW`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw) and see if the same error occurs?

**Comment by TechStudent10** [comment]
> So your injector is 64-bit and both the payload and target is 32-bit?

Yes

**Comment by TechStudent10** [comment]
> Can you try to load your dll with the same path in a small test program using [`LoadLibraryW`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw) and see if the same error occurs?

Oh you mean in C++? I could try that

**Comment by OpenByteDev** [comment]
Did you try it?

**Comment by TechStudent10** [comment]
> Did you try it?

Not yet sorry. Wasn't feeling well after the response so I wasn't on my computer for a bit.
