### ISSUE TITLE
Injecting a 64bit dll into a 32bit process

### ISSUE THREAD

**Issue by Zabaniya001** [OpenByteDev/dll-syringe#18]
Hello. I'm having a hard time figuring out how to inject 64bit DLLs into a 32bit application without running against "**ArchitectureMismatch**", and I'm not finding any examples on Github or the Rust discord server to learn from.

Basically:
- The injector app is 64bit.
- The DLL I'm trying to inject is 64bit.
- The app that I'm targeting ( a game ) is 32bit.

In the docs `into-x86-from-x64` gets mentioned, but I'm unsure where and how to use it. I enabled it as a feature for the dependency and tried to use it with #[cfg(features="into-x86-from-x64")]. But once I hover it, it says that it's disabled.
I also tried to just compile everything as 32bit by targeting `--target=i686-pc-windows-msvc`, but that doesn't seem to do anything either.

I'm sorry for opening this issue, especially if the answer is obvious, but I'm out of options and I'd like to use this library to try out some stuff.

**Comment by OpenByteDev** [comment]
That is because injecting a dll compiled for a different architecture than the process you want to inject in is not supported.
The feature `into-x86-from-x64` only allows the injector process to be x64 for x32 targets.
The payload dll **always** has to match the target process architecture.
