### ISSUE TITLE
Consider switching to windows-sys

### ISSUE THREAD

**Issue by philpax** [OpenByteDev/dll-syringe#2]
Hello again!

Was just looking at the dependency tree for my project and noticed that `dll-syringe` uses `winapi`, which hasn't been updated in [over a year](https://crates.io/crates/winapi). It looks like the rest of the ecosystem is transitioning to `windows-rs`, and its `sys` companion, [`windows-sys`](https://docs.rs/windows-sys/latest/windows_sys/).

I'd suggest switching over so that you can benefit from the updates. The recommendation seems to be to use `sys` for crates to avoid the compile-time hit, which is why I'm suggesting that over `windows-rs` itself.

**Comment by OpenByteDev** [comment]
I dont really think that the `winapi` crate is bad just because it has not been updated for a while as the windows apis don't really change.

Therefore i dont really see enought benefit for the amount of work the switch would require.

**Comment by philpax** [comment]
I wouldn't say it's bad so much as it's nice to standardise on one thing and removing duplication in the dependency tree. Would you accept a PR switching over to `windows-sys`?

**Comment by OpenByteDev** [comment]
Sure
