### ISSUE TITLE
Inject fails with "not a valid Win32 application"

### ISSUE THREAD

**Issue by bonega** [OpenByteDev/dll-syringe#3]
`remote io error: %1 is not a valid Win32 application. (os error 193)`

This is specific to a game called "the binding of isaac".
Processname is "isaac-ng" and shows up as a 32bit application in task manager.

I can inject successfully into "explorer" for example.
Tried enabling feature `into-x86-from-x64` without any luck.

Host: Windows 10 64bit

Thanks for any help

**Comment by OpenByteDev** [comment]
Is the payload dll you are trying to inject 32 bit as well?

**Comment by bonega** [comment]
It was not, thanks for that.

Now I am running: `cargo build --target=i686-pc-windows-msvc`

But still get another error: `The system cannot find the file specified. (os error 2)`
This is not the same as wrong path to the .dll

**Comment by OpenByteDev** [comment]
Are you maybe using a relative path that cannot be resolved from the context of the target process?

**Comment by bonega** [comment]
I am using a relative path  `./target/i686-pc-windows-msvc/debug/irestart.dll`
Tried to change it to an absolute path with same result.

But even with the relative path I get different results for:  `./target/i686-pc-windows-msvc/debug/irestart.dll` 
vs
`./target/i686-pc-windows-msvc/debug/doesnotexist.dll`

First example is: cannot find file (os error 2)
Second is: cannot find module (os error 126)

I upload a repo: https://github.com/bonega/irestart

**Comment by fasterthanlime** [comment]
@bonega here are things I would try:

  * Run ProcMon and look for error return codes in isaac-ng when injecting: https://docs.microsoft.com/en-us/sysinternals/downloads/procmon
  * Try to LoadLibrary your DLL directly from an executable you've coded yourself
  * Try to inject it into another executable (maybe a 64-bit one)
  * Use `dumpbin /imports` on your DLL (from an MSVC developer tools shell for x86), or use Dependency Walker or a modern equivalent

**Comment by OpenByteDev** [comment]
Can you try your code in release mode?

**Comment by bonega** [comment]
@OpenByteDev --release for the injector solved it, thank you very much.

@fasterthanlime Thanks for the general tips.
In your video, are you running the injector in release mode? I couldn't see it.

**Comment by OpenByteDev** [comment]
The error seems to be with the debug_assert in `Syringe::inject`.

**Comment by OpenByteDev** [comment]
The error seems to be with the debug_assert in `Syringe::inject`.

**Comment by fasterthanlime** [comment]
> In your video, are you running the injector in release mode? I couldn't see it.

Mhh no I even had a bit (that I cut) about how you normally would want release mode but it was so little code that it didn't actually slow down the emulator enough for me to care.

(Context for everyone else: @bonega is talking about [this video](https://fasterthanli.me/videos/getting-good-at-snes))

**Comment by OpenByteDev** [comment]
Fixed in `0.11.2`
