### ISSUE TITLE
Invalid access to memory location.

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [OpenByteDev/dll-syringe#31]
Hi, I managed to find the missing DLL files, but now I'm getting this error message:

```
src/main.rs:9:5] metadata.is_file() = true
thread 'main' panicked at src/main.rs:15:98:
called `Result::unwrap()` on an `Err` value: RemoteIo(Os { code: 998, kind: Uncategorized, message: "Invalid access to memory location." })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\injection-dll.exe .` (exit code: 101)
```

**Comment by OpenByteDev** [comment]
Is it still the same code you shared previously?

**Comment by OpenByteDev** [comment]
Is the dll written by you or do you know its source code?

**Comment by OpenByteDev** [comment]
Can you try to inject the dll into another process and inject another dll into your target process?

**Comment by RiritoXXL** [comment]
I don't have any problem here, but maybe because Anticheat is protecting some memory or maybe because architecture type is not supported!!!

**Comment by RiritoXXL** [comment]
> > I don't have any problem here, but maybe because Anticheat is protecting some memory or maybe because architecture type is not supported!!!
> 
> the dll used to work on windows 7

oh okay

**Comment by RiritoXXL** [comment]
> > > > I don't have any problem here, but maybe because Anticheat is protecting some memory or maybe because architecture type is not supported!!!
> > > 
> > > 
> > > the dll used to work on windows 7
> > 
> > 
> > oh okay
> 
> I haven't written the DLL and I can't tell anything from code returned by decompilers. It's really tricky.

try install Windows 10, install VS 2022 Professional with All Packages and try compile dll again!!!
