### ISSUE TITLE
> > > > I don't have any problem here, but maybe because Anticheat is protecting some memory or maybe because architecture type is not supported!!!

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [OpenByteDev/dll-syringe#32]
> > > > I don't have any problem here, but maybe because Anticheat is protecting some memory or maybe because architecture type is not supported!!!
> > > 
> > > 
> > > the dll used to work on windows 7
> > 
> > 
> > oh okay
> 
> I haven't written the DLL and I can't tell anything from code returned by decompilers. It's really tricky.

try install Windows 10, install VS 2022 Professional with All Packages and try compile dll again!!!

_Originally posted by @RiritoXXL in https://github.com/OpenByteDev/dll-syringe/issues/31#issuecomment-2488421435_

but it's not my dll I didn't compile it.

**Comment by RiritoXXL** [comment]
lol, whose is it then?

**Comment by RiritoXXL** [comment]
> > lol, whose is it then?
> 
> unclear, some guy called afirenice who gave it to a friend, who gave it to a friend, who gave it to me.

LOL... you can create you're own dll and inject via dll-syringe again

**Comment by RiritoXXL** [comment]
> > > > lol, whose is it then?
> > > 
> > > 
> > > unclear, some guy called afirenice who gave it to a friend, who gave it to a friend, who gave it to me.
> > 
> > 
> > LOL... you can create you're own dll and inject via dll-syringe again
> 
> yeah thats hard because I don't know how long the reverse engineering might take. It's many memory locations.

okay...

**Comment by RiritoXXL** [comment]
> > > > > > lol, whose is it then?
> > > > > 
> > > > > 
> > > > > unclear, some guy called afirenice who gave it to a friend, who gave it to a friend, who gave it to me.
> > > > 
> > > > 
> > > > LOL... you can create you're own dll and inject via dll-syringe again
> > > 
> > > 
> > > yeah thats hard because I don't know how long the reverse engineering might take. It's many memory locations.
> > 
> > 
> > okay...
> 
> maybe delete the issue thx.

you're welcome!!!
